- alias: "Coming home"
  trigger:
    platform: state
    entity_id: group.wrang
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"
      - condition: time
        before: '23:00:00'
      - condition: state
        entity_id: group.all_lights
        state: 'off'
  action:
    service: light.turn_on
    entity_id: group.homecoming
